name: Format & Lint
description: Format and lint code

runs:
  using: 'composite'
  steps:
    - name: Format and lint code
      run: |
        npm run lint:fix
        npm run format
      shell: bash
